logging:
    file:
        name: /logs/letteon.log
    level:
        jdbc:
            resultsettable: debug
            sqlonly: debug
            sqltiming: debug
        root: info
        org.springframework.web: debug

server:
    port: 8080
    servlet:
        context-path: /lotteon
    error:
        whitelabel:
            enabled: false
        path: error


spring:
    application:
        name: lotteon-team4
        version: ${version}
    devtools:
        livereload:
            enabled: true

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: "Choasa15!"
        url: jdbc:mysql://13.125.226.80:3306/lotteon
        username: root

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    servlet:
        session:
            timeout: 10m
        # 파일 업로드 설정
        multipart:
            max-file-size: 10MB     # 업로드 파일의 최대 크기
            max-request-size: 15MB  # 요청 전체 크기
            location: uploads/
            # location : /home/ec2-user/uploads/
           #location: 배포 시 절대 경로로 바꿔주는 것이 좋음
    web:
        resources:
            static-locations:
                - classpath:/static/
    thymeleaf:
        cache: false
        check-template-location: true
        enabled: true
        prefix: classpath:/templates
        suffix: .html


    mail:
        host: smtp.gmail.com
        port: 587
        username: rkddmsrud27@gmail.com
        password: wmasglmphptyyshf # google 앱 비밀번호
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 735533272101-jmn7ronqp4q43gbaihgb652kbs9skr7f.apps.googleusercontent.com
                        client-secret: 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
                        redirect-uri: http://ec2-13-125-226-80.ap-northeast-2.compute.amazonaws.com:8080/lotteon/login/oauth2/code/google
                        scope:
                            - email
                            - profile
                    kakao:
                        client-id: c56f604e9e2dbda714e9198ca2579d5a
                        client-secret: THvJHmr3e2C1WyezpEQzCZHavkapYBTt
                        scope:
                            - profile_nickname
                            - account_email
                        redirect-uri: http://ec2-13-125-226-80.ap-northeast-2.compute.amazonaws.com:8080/lotteon/login/oauth2/code/kakao
                        authorization-grant-type: authorization_code
                        client-authentication-method: client_secret_post
                        client-name: Kakao
                    naver:
                        client-id: pnQaty7K2BUoFSfyq00V
                        client-secret: KcIvxrUr85
                        scope:
                            - name
                            - email
                        redirect-uri: http://ec2-13-125-226-80.ap-northeast-2.compute.amazonaws.com:8080/lotteon/login/oauth2/code/naver
                        authorization-grant-type: authorization_code
                        client-name: Naver
                provider:
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: name
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    naver:
                        authorization_uri: https://nid.naver.com/oauth2.0/authorize
                        token_uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user_name_attribute: response
    data:
        redis:
            lettuce:
                pool:
                    max-active: 5
                    max-idle: 5
                    min-idle: 5
            host: 13.125.226.80
            port: 6379

        mongodb:
            uri: mongodb://lotteon:1234@13.125.226.80:27017/lotteon?authSource=lotteon
